config/routes.rb
Rails.application.routes.draw do
  root 'states#new'

  resources :states
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :district

  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, length: { is: 5 }, numericality: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :addresses
  attr_accessor :rep, :sen1, :sen2

  validates :zip_code, presence: true, length: { is: 5 }, numericality: true
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :addresses
  
  attr_accessor :rep, :sen1, :sen2

  validates :zip_code, presence: true, length: { is: 5 }, numericality: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  require 'net/http'
  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    api_data = Net::HTTP.get_response(URI("https://www.googleapis.com/civicinfo/v2/representatives?address=#{@address}&includeOffices=true&levels=subLocality2&levels=subLocality1&roles=legislatorLowerBody&roles=legislatorUpperBody&roles=schoolBoard&fields=offices%2Cofficials&key={AIzaSyAzJV6jWvLWfcufzy3ug2ghJ-uBTX2YsHw}"))
    result = JSON.parse(api_data.body)
    @district = result

    if @address.valid?
      @address.save
      flash[:notice] = "Address added successfully"
      redirect_to districts_path(@district)
    else
      flash[:notice] = @address.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def show
    @state = State.find(params[:id])
    zip_code = @state.zip_code
    api_data = Net::HTTP.get_response(URI("http://whoismyrepresentative.com/getall_mems.php?zip=#{zip_code}&output=json"))
    result = JSON.parse(api_data.body)
    @state.rep_name = result['results'][0]['name']
    @state.rep_state = result['results'][0]['district']
    @state.rep_phone = result['results'][0]['phone']
    @state.rep_link = result['results'][0]['link']
    @state.rep_state = result['results'][0]['state']
    @state.sen1_name = result['results'][1]['name']
    @state.sen1_seat = result['results'][1]['district']
    @state.sen1_phone = result['results'][1]['phone']
    @state.sen1_link = result['results'][1]['link']
    @state.sen2_name = result['results'][2]['name']
    @state.sen2_seat = result['results'][2]['district']
    @state.sen2_phone = result['results'][2]['phone']
    @state.sen2_link = result['results'][2]['link']
  end

  def create
    zip_code = params[:district][:zip_code]
    @state = State.new(district_params)
    api_data = Net::HTTP.get_response(URI("http://whoismyrepresentative.com/getall_mems.php?zip=#{zip_code}&output=json"))
    result = JSON.parse(api_data.body)
    @state.rep = result['results'][0]
    @state.sen1 = result['results'][1]
    @state.sen2 = result['results'][2]
    if @state.save
      redirect_to state_path(@state)
    elsif @state.empty?
      redirect_to root_path
    else
      flash[:notice] = @state.errors.full_messages.join(", ")
      render :create
    end
  end

  def destroy
    State.destroy(params[:id])
    redirect_to states_path
  end

  private

  def state_params
    params.require(:state).permit(:zip_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.erb
<% @address.each do |a| %>
<%= address.street %>
<% end %>

app/views/addresses/new.html.erb
<h1>Enter Your Information Here</h1>

<%= form_for(@address) do |f| %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>

  <%= f.submit "Submit" %>
<% end %>

<%= flash[:notice] %>

app/views/districts/_form.html.erb
<%= form_for(@district) do |f|%>
  <%= f.text_field :zip_code, class: 'zip' %>
  <%= f.submit "Submit", class: 'button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Government Official Findr" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="fixed">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h4><a href="#"><%= link_to "Government Official Findr", root_path %></a></h4>
        </li>
      </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="active"><a href="#"><%= link_to "Home", root_path %></a></li>
      <li><a href="#"><%= link_to "Index", states_path %></a></li>
    </ul>
  </section>
</nav>
</div>

    <%= yield %>

  </body>
</html>

app/views/states/_form.html.erb
<%= form_for(@state) do |f|%>
  <%= f.text_field :zip_code, class: 'zip' %>
  <%= f.submit 'Submit', class: 'button' %>
<% end %>

app/views/states/index.html.erb
<div class='info'>
<h1 class='district index'>Zip Codes</h1>
<% @states.each do |state| %>
<li class='index'><%= link_to "#{state.zip_code}", state %></li>
<% end %>
<br></br>
<li class='link'><%= link_to "Enter New Zip Code", new_state_path, class: 'new-zip-link' %>
</div>

app/views/states/new.html.erb
<h2 class='new title'>Enter Your 5-Digit Zip Code</h2>
<%= render 'form' %>

app/views/states/show.html.erb
<div class='info'>
<div class='rep'>
<li class='Rep'><%= "Your Representative in the House is #{@district.rep_name}" %></li>
<li class='Rep'><%= "Your House district is #{@district.rep_state}-#{@district.rep_district}" %></li>
<li class='Rep'><%= "Their phone number is #{@district.rep_phone}" %></li>
<a href=<%= @district.rep_link%>>Click here for more info</a>
</div>
<br></br>
<div class='sen1'>
<li><%= "One of your Senators is #{@district.sen1_name}" %></li>
<li><%= "Their seat is the #{@district.sen1_seat}" %></li>
<li><%= "Their phone number is #{@district.sen1_phone}" %></li>
<a href=<%= @district.sen1_link%>>Click here for more info</a>
</div>
<br></br>
<div class='sen2'>
<li><%= "Your other Senator is #{@district.sen2_name}" %></li>
<li><%= "Their seat is the #{@district.sen2_seat}" %></li>
<li><%= "Their phone number is #{@district.sen2_phone}" %></li>
<a href=<%= @district.sen2_link%>>Click here for more info</a>
</div>
<br></br>
<li class='link'><%= link_to "Zip Code Index", districts_path %>
<li class='link'><%= link_to "Enter New Zip Code", new_district_path %>
</div>
<div class='link'><%= form_for([@district], method: 'delete') do |f| %>
  <%= f.submit 'Delete Zip', class: 'delete-button' %>
  <% end %>